### ISSUE TITLE
Image Circle Button after OnClick turning into Square Button

### ISSUE THREAD

**Issue by Charuwaka** [wilsonvargas/ButtonCirclePlugin#23]
![screenshot_1516602815](https://user-images.githubusercontent.com/32363595/35208768-ebca259e-ff6f-11e7-887a-e395438bdf3d.png)
![screenshot_1516602818](https://user-images.githubusercontent.com/32363595/35208769-ec279800-ff6f-11e7-93da-f9ac7026a2ad.png)

**Comment by wilsonvargas** [comment]
Does this happen with an icon or with an image?

**Comment by Charuwaka** [comment]
@wilsonvargas  with Image

**Comment by DiegoJGG** [comment]
Any updates ? @wilsonvargas

**Comment by wilsonvargas** [comment]
Yes, this issue is solved by assigning a style like "**NoShadow**" in your `style.xml` file:

```xml
<style name="NoShadowButton" parent="android:style/Widget.Button">
        <item name="android:stateListAnimator">@null</item>
</style>
```

And then set this style to `android:buttonStyle` in your main style, like this:
```xml
<item name="android:buttonStyle">@style/NoShadowButton</item>
```

For more information see [this sample file](https://github.com/wilsonvargas/ButtonCirclePlugin/blob/master/test/TestAppButtonCircle/TestAppButtonCircle.Android/Resources/values/styles.xml)

**Comment by Charuwaka** [comment]
Thank 's for update @wilsonvargas
