### ISSUE TITLE
UWP Release Mode Not Working With Circle Button Why? 

### ISSUE THREAD

**Issue by GreenTea66** [wilsonvargas/ButtonCirclePlugin#26]
please help me to solve the problem!

![debug](https://user-images.githubusercontent.com/19529061/35855154-b01034f2-0b32-11e8-9d85-7b78eea8ecdc.PNG)
![release](https://user-images.githubusercontent.com/19529061/35855155-b0264a26-0b32-11e8-8080-8509139511f7.PNG)

**Comment by GreenTea66** [comment]
why no answer  ?

**Comment by kvpt** [comment]
It's a classic .NetNative (the runtime UWP release mode use) issue.
The toolchain linker don't detect that the code is used and delete it. (Because the renderer is injected by 
the framework).
It's for this reason that the renderer has an static Init method, to help the compiler to notice that the renderer is used.

This missing in the doc but you need this code in UWP too.
ButtonCircleRenderer.Init();
