### ISSUE TITLE
Target framework issue

### ISSUE THREAD

**Issue by stesvis** [wilsonvargas/ButtonCirclePlugin#29]
Hi,

I get this build warning lately, is there some incompatibility?

> Package 'Plugins.Forms.ButtonCircle 1.3.9' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by wilsonvargas** [comment]
This is because you use .netstandard in your main project. You must download the beta version of this plugin to eliminate that warning.

Click right in your solution -> Manage Nuget Package -> check **Include prerelease** option and download **2.0.1.48-beta** version

![capture](https://user-images.githubusercontent.com/22247447/36759719-5ac17b54-1be6-11e8-9521-add1f7f4add4.PNG)
